### ISSUE TITLE
Speech coding and decoding ，Will the efficiency be very low ？

### ISSUE THREAD

**Issue by sunjunlishi** [googlesamples/assistant-sdk-cpp#10]
converse_config->mutable_audio_in_config()->set_encoding(
			AudioInConfig::LINEAR16);
		converse_config->mutable_audio_in_config()->set_sample_rate_hertz(16000);
		converse_config->mutable_audio_out_config()->set_encoding(
			AudioOutConfig::LINEAR16);
		converse_config->mutable_audio_out_config()->set_sample_rate_hertz(16000);

Will the efficiency be very low For the network ？

**Comment by Fleker** [comment]
Are you concerned with the amount of data being transmitted on the network?

The gRPC API is designed to be very lightweight and minimize data being sent.

**Comment by sunjunlishi** [comment]
converse_config->mutable_audio_in_config()->set_encoding(
		AudioInConfig::LINEAR16);
	converse_config->mutable_audio_in_config()->set_sample_rate_hertz(16000);
	converse_config->mutable_audio_out_config()->set_encoding(
		AudioOutConfig::MP3);
	converse_config->mutable_audio_out_config()->set_sample_rate_hertz(16000);

AudioOutConfig::MP3 The receiving speed is very fast

**Comment by sunjunlishi** [comment]
The input is only supported by FLAC, and I will try
