### ISSUE TITLE
assistant_sdk failed, error: Error in HTTP transport completing operation

### ISSUE THREAD

**Issue by sunjunlishi** [googlesamples/assistant-sdk-cpp#11]
assistant_sdk failed, error: Error in HTTP transport completing operation

**Comment by Fleker** [comment]
Can you provide more information about why this error occurred?

**Comment by sunjunlishi** [comment]
I deliberately tested the broken net ,When the network is good, grpc will automatically connect .
Although he had a little impact on my Internet socket, it was later OK

**Comment by sunjunlishi** [comment]
stream1 = std::shared_ptr<ClientReaderWriter<ConverseRequest, ConverseResponse>>(std::move(assistant->Converse(context)));
		::google::assistant::embedded::v1alpha1::ConverseConfig* converse_config = request1.mutable_config();
		converse_config->mutable_audio_in_config()->set_encoding(
			AudioInConfig::LINEAR16);
		converse_config->mutable_audio_in_config()->set_sample_rate_hertz(16000);
		converse_config->mutable_audio_out_config()->set_encoding(
			AudioOutConfig::MP3);
		converse_config->mutable_audio_out_config()->set_sample_rate_hertz(16000);
		stream1->Write(request1);


#Sleep(5 second)
 
             while (stream1->Read(&response))
             {}

             grpc::Status status = stream1->Finish();
		if (!status.ok()) {
			// Report the RPC failure.
			std::cerr << "assistant_sdk failed, error: " <<
				status.error_message() << std::endl;
			return;
		}


if sleep than more 5 seconde  than error error: Error in HTTP transport completing operation
  grpc::Status status = stream1->Finish();
		if (!status.ok()) {
			// Report the RPC failure.
			std::cerr << "assistant_sdk failed, error: " <<
				status.error_message() << std::endl;
			return;
		}

**Comment by Fleker** [comment]
If there is no response on the network from the gRPC call after a time, the connection will timeout.

**Comment by sunjunlishi** [comment]
you see from one side,i see. but  do you test in thread and for many times.have you  thought that

**Comment by Fleker** [comment]
The sample app is designed to be a simple demonstration of the gRPC calls in C++. For a more robust implementation one may need to implement additional features.

**Comment by sunjunlishi** [comment]
“one may need to implement additional features.”  so hard, assistant grpc ,c++ template
