### ISSUE TITLE
oauth 2 token error?

### ISSUE THREAD

**Issue by sunjunlishi** [googlesamples/assistant-sdk-cpp#12]
assistant_sdk failed, error: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

All of a sudden it can't be used

**Comment by sunjunlishi** [comment]
./get_credentials.shClient id: 259447142563-k36a08ij3euk1b0josfb5jqsgn78c5so.apps.googleusercontent.com
Client secret: 5paR8McY2DPi8uvcb1VE-ej-

Please go to the following link to authorize, and copy back the code here:
https://accounts.google.com/o/oauth2/v2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fassistant-sdk-prototype&access_type=offline&include_granted_scopes=true&state=state&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&client_id=259447142563-k36a08ij3euk1b0josfb5jqsgn78c5so.apps.googleusercontent.com

Code: 4/cPIVe094AGb8JZ_cf7ZLgb3yrzqWIkv2EBFT38lfldo

**Comment by Fleker** [comment]
What command are you using? Are you using `--credentials_type USER_ACCOUNT`?

Also, you should refrain from posting specific authentication tokens and URLs publicly.

**Comment by sunjunlishi** [comment]
YES

**Comment by sunjunlishi** [comment]
assistant_sdk wrote first request: config { audio_in_config { encoding: LINEAR16 sample_rate_hertz: 16000 } audio_out_config { encoding: LINEAR16 sample_rate_hertz: 16000 } converse_state { context { } } }
AudioOutputALSA Start() succeeded
assistant_sdk waiting for response ... 
AudioOutputALSA Stop() succeeded
assistant_sdk failed, error: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
terminate called without an active exception

**Comment by sunjunlishi** [comment]
I followed you:
For end-user's credentials:

    1 Download the client secret json file from Google Cloud Platform Console following these instructions
    2 Move it in this folder and rename it to client_secret.json
   3  run get_credentials.sh in this folder. It will create the file credentials.json.


and All of a sudden it can't be used

**Comment by sunjunlishi** [comment]
Can you try with the other audio sample, ./run_assistant --audio_input ./resources/weather_in_mountain_view.raw --credentials_file ./credentials.json --credentials_type USER_ACCOUNT and see if the behavior is the same? same error

over the 500 maximum queries per day? no

Is the Google Cloud Project you are using have the Google Assistant API enabled? yes


i have said that before ok,sudden error.

would you have a try ?

**Comment by sunjunlishi** [comment]
![1](https://user-images.githubusercontent.com/11845664/33693703-3a3cf9f0-db2f-11e7-9791-7340a0ab01b5.png)

**Comment by sunjunlishi** [comment]
![3](https://user-images.githubusercontent.com/11845664/33695522-c3be2434-db38-11e7-89b8-60529532f152.png)

**Comment by project-owner** [comment]
Same here. To reproduce just run one of your examples - pushtotalk.py. It's not working anymore.

**Comment by Fleker** [comment]
We are aware of this issue. Let's keep tracking it in the Python issue, as the issue is technically the same. I'll post updates there.

https://github.com/googlesamples/assistant-sdk-python/issues/138

**Comment by sunjunlishi** [comment]
it is ok,thank you
