### ISSUE TITLE
google.assistant.embedded.v1alpha1 is deprecated

### ISSUE THREAD

**Issue by shihancheng** [googlesamples/assistant-sdk-cpp#14]
google.assistant.embedded.v1alpha1 is deprecated. Will google.assistant.embedded.v1alpha2 available soon?

**Comment by Fleker** [comment]
Yes we've just deprecated v1alpha1 and are going to be updating this sample with v1alpha2 soon.

**Comment by shihancheng** [comment]
Thanks. I have just did it on my own code. If need any help please let me know.

**Comment by Fleker** [comment]
v1alpha2 is now available in the project
