### ISSUE TITLE
Handle a single request and no hotword detection?

### ISSUE THREAD

**Issue by subjectxbj** [googlesamples/assistant-sdk-cpp#17]
Hi,
I checked the code, seems this sample can only handle the single command. After handle the request, it will exit. And there is no hotword detection.

Is there a full sample that can detect the hotword "Hi Google" and always listen to the microphone, without manually start up the app?

**Comment by Fleker** [comment]
This is currently the only sample for C++ and it uses the Google Assistant Service API. Hotword detection is probably not going to be added to this sample. There are many ways that it can be done, in software or hardware, depending on the setup.

Handling more than one command is a feature request that has been brought up before. It's been a bit lower priority compared to other projects. However, I hope this sample is simple enough that you can see how to do the follow-up requests yourself.

**Comment by subjectxbj** [comment]
@Fleker , Thanks for response.
