### ISSUE TITLE
No rule to make target 'src/service_account_util.o', needed by 'run_assistant'.

### ISSUE THREAD

**Issue by rajesh1006** [googlesamples/assistant-sdk-cpp#18]
In the src/ folder service_account_util.cc and service_account_util.h files are missing.

**Comment by rajesh1006** [comment]
I hope removing the "./src/service_account_util.o" from the Makefile solves this issue.

**Comment by Fleker** [comment]
I'm going to release a few patches to the sample in a few hours that should fix build issues. Using service accounts are not supported in this sample.

**Comment by Fleker** [comment]
Should be corrected in the latest set of changes.
