### ISSUE TITLE
Compiloe error&Oauth error

### ISSUE THREAD

**Issue by athul7pk** [googlesamples/assistant-sdk-cpp#2]
1. I am getting error: ‘google::assistant::embedded::v1alpha1::DeviceConfig’ has not been declared
     using google::assistant::embedded::v1alpha1::DeviceConfig;
     removing that line works fine .
2. While running  run_assistant --audio_input ALSA_INPUT --credentials_file ./credentials.json --credentials_type USER_ACCOUNT
 getting assistant_sdk failed, error: Error occured when fetching oauth2 token.
 oauth_fetch: {"created":"@1504611219.493506582","description":"OS Error","errno":-2,"file":"src/core                                                     /lib/iomgr/resolve_address_posix.c","file_line":119,"os_error":"Name or service not known","syscall":"getaddrinfo","target_address":"www.googleapis.com"}

**Comment by Fleker** [comment]
On what device are you running this?

**Comment by sunjunlishi** [comment]
(required by /usr/local/lib/libgrpc.so.4)
assistant_sdk robots_pem: 
assistant_sdk CreateCustomChannel(embeddedassistant.googleapis.com:443, creds, arg)

E1125 21:57:19.169789182    3080 ssl_transport_security.c:940] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.

**Comment by sunjunlishi** [comment]
i have resolve it. I install curl-7.56.1,and then install grpc. It has successfully

**Comment by athul7pk** [comment]
Sorry
I was using raspberry pi 0w with rasbian OS
...thank you both for your reply
Sunjunlishis solution s seems. Good.. Thank you
