### ISSUE TITLE
run_assistant ssl error

### ISSUE THREAD

**Issue by jimmyxukui** [googlesamples/assistant-sdk-cpp#21]
I ported this sample on arm linux(yocto) platform,but when I run this sample,it shows errors like below.Can someone help?Thanks a lot. 

assistant_sdk robots_pem: 
assistant_sdk CreateCustomChannel(embeddedassistant.googleapis.com:443, creds, arg)

E0101 00:37:40.523319895    2771 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E0101 00:37:40.675959062    2771 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E0101 00:37:43.238969738    2771 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificat

**Comment by Fleker** [comment]
Seems like you have an issue making a secure connection to the server. You may have an issue with your system date or your Internet connection. You should check those things.

**Comment by jimmyxukui** [comment]
Thanks for your reply.It was fixed by setting date.
