### ISSUE TITLE
get_credentials.sh is outdated

### ISSUE THREAD

**Issue by tamama** [googlesamples/assistant-sdk-cpp#24]
Hi, 

It seems that get_credentials.sh is outdated with the newer version of client key-json without client_secret field.

May I have an easy guide of how to generate the credentials.json needed for run_assistant?

Kind regards,
Tamama

**Comment by Fleker** [comment]
I'm not sure I understand what this newer version includes. I have not had issues running the shell script and getting the `credentials.json`.

The format for the file is

```
{
  "client_id": "$CLIENT_ID",
  "client_secret": "$CLIENT_SECRET",
  "refresh_token": "$REFRESH_TOKEN",
  "type": "authorized_user"
}
```

**Comment by tamama** [comment]
Hi Fleker, 

Following the docs, I get the following secret json file for my service account:

{
  "type": "service_account",
  "project_id": "$PROJECT_ID",
  "private_key_id": "PRIVATE_KEY_ID",
  "private_key": "$PRIVATE_KEY",
  "client_email": "$CLIENT_EMAIL",
  "client_id": "$CLIENT_ID",
  "auth_uri": "$AUTH_URI",
  "token_uri": "$TOKEN_URI",
  "auth_provider_x509_cert_url": "$AUTH_PROVIDER_X509_CERT_URL",
  "client_x509_cert_url": "$CLIENT_X509_CERT_URL"
}

**Comment by Fleker** [comment]
The instructions were designed to use a user's account, not a service account. It does seem like I will need to clean-up the README.

**Comment by tamama** [comment]
![image](https://user-images.githubusercontent.com/17287685/39337665-c47c7354-49f0-11e8-9113-e7ce3959b04e.png)

**Comment by tamama** [comment]
Hi Fleker,

Can I confirm with you that it is 

![image](https://user-images.githubusercontent.com/17287685/39337796-85a1d0f6-49f1-11e8-88bf-30dbe3b33b26.png)

**Comment by Fleker** [comment]
Yeah that should be fine, but then you'll need to download the client secret and then generate the credentials.

**Comment by tamama** [comment]
Let me try in a moment and get back to you today.

**Comment by tamama** [comment]
This solves it.
