### ISSUE TITLE
run_assistant with "Prive managers HK" fails to get response

### ISSUE THREAD

**Issue by tamama** [googlesamples/assistant-sdk-cpp#27]
Hi,

Today, I try to run_assistant with "Prive managers HK" text_input. No response gets back. May I know how to fix this?
+ The logs are attached as below.

Kind regards,
Tamama

============
text_input "Prive managers HK"    -- NOT OKAY
============
[root@e74af657915f assistant-sdk-cpp]# LD_LIBRARY_PATH=runtime bin/run_assistant --text_input "Prive managers HK" --credentials_file asset/credentials.json --verbose
Using locale en-US
assistant_sdk robots_pem: 
assistant_sdk CreateCustomChannel(embeddedassistant.googleapis.com:443, creds, arg)

assistant_sdk wrote first request: config { audio_out_config { encoding: LINEAR16 sample_rate_hertz: 16000 } dialog_state_in { language_code: "en-US" } device_config { device_id: "default" device_model_id: "default" } text_query: "Prive managers HK" }
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM default
AudioOutputALSA snd_pcm_open returned -2
assistant_sdk waiting for response ... 
assistant_sdk Got a response 

============
text_input "What time is it?"    -- Works OKAY
============
[root@e74af657915f assistant-sdk-cpp]# LD_LIBRARY_PATH=runtime bin/run_assistant --text_input "What time is it" --credentials_file asset/credentials.json --verbose
Using locale en-US
assistant_sdk robots_pem: 
assistant_sdk CreateCustomChannel(embeddedassistant.googleapis.com:443, creds, arg)

assistant_sdk wrote first request: config { audio_out_config { encoding: LINEAR16 sample_rate_hertz: 16000 } dialog_state_in { language_code: "en-US" } device_config { device_id: "default" device_model_id: "default" } text_query: "What time is it" }
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM default
AudioOutputALSA snd_pcm_open returned -2
assistant_sdk waiting for response ... 
assistant_sdk Got a response 
assistant_sdk response:
The time is 10:39 AM.

**Comment by Fleker** [comment]
"Prive managers HK" is an address?

**Comment by tamama** [comment]
1.  That is a Hong Kong company.
2.  Shouldn't the response be "Sorry, I don't understand what that means." ?

**Comment by Fleker** [comment]
If I do it on my phone, it does understand it. It shows the location. It seems like certain queries such as maps may not be returning text right now.

**Comment by Fleker** [comment]
I'm not sure if the response publicly has that data right now.
