### ISSUE TITLE
POP noise at the end Google Feedback response

### ISSUE THREAD

**Issue by rajesh1006** [googlesamples/assistant-sdk-cpp#29]
After some analysis, I confirm that there is a pop like noise at the end of google feedback response particularly for the responses of "what is the time".
Here I have confirmed that the noise data looks like an audio sample.
It doesn't match with the noise data of Capacitor switching drain.
This POP like noise arrives once the snd_pcm_drain is called.

Here I'm running this SDK as a loop to generate the continuous feedback response.
I tried my possible methods to find the reason, but I couldn't proceed further.
Seeking your support regarding this.

**Comment by Fleker** [comment]
Where are you running this? Can you see if it's part of the actual response coming from the response or something that happens when playing back the audio?

**Comment by rajesh1006** [comment]
I'm running this on i.Mx7D platform with Yocoto based Linux build.
This issue happens at the end of google assistant's voice response.
eg. <The time is xx.xx "POP">.

**Comment by Fleker** [comment]
Do you think this is related to something on your device's sound system when closing an audio stream?

**Comment by rajesh1006** [comment]
Yes, this is solved.
There were two reasons behind this.
1) Common Mode Noise at the Headphones out.
2) Thread writing Audio Output is blocked.

After addressing Common Mode Noise by removing the unwanted capacitor and Increasing the Audio Output thread priority, this issue is solved.

Thanks for your Support.
