### ISSUE TITLE
Why googleapi does not provide the device control interfaces?

### ISSUE THREAD

**Issue by subjectxbj** [googlesamples/assistant-sdk-cpp#34]
I notice google has defined device control interfaces for assistant service
https://developers.google.com/assistant/sdk/reference/rpc/google.assistant.devices.v1alpha2

But I did not find the interfeace definition in the googleapi. So I'm not able to create devices with assistant service. I need to use the tool "googlesamples-assistant-devicetool" on a python environment to register the device.

Thanks,
Arthman

**Comment by Fleker** [comment]
This is related to an issue in the [Python sample](https://github.com/googlesamples/assistant-sdk-python/issues/247). You can use [a REST API](https://developers.google.com/assistant/sdk/reference/device-registration/register-device-manual) to make calls for device registration, which is what the [devicetool](https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/devicetool.py) does.

**Comment by subjectxbj** [comment]
Thanks
