### ISSUE TITLE
GPR_ERROR, 'https' scheme not supported in proxy URI

### ISSUE THREAD

**Issue by joy12202018** [googlesamples/assistant-sdk-cpp#39]
Followed by the README to set up, went to the seventh part and went wrong.
$ ./run_assistant_file --input ./resources/weather_in_mountain_view.raw --output ./response.wav \
--credentials ./credentials.json
E0809 10:40:17.892764613   75696 http_proxy.cc:62]           'https' scheme not supported in proxy URI

then hanged
My operating system Ubuntu16.04

**Comment by Fleker** [comment]
Are you using some sort of web proxy?

**Comment by joy12202018** [comment]
yes

**Comment by joy12202018** [comment]
Is there any way to solve this problem?

**Comment by joy12202018** [comment]
I am using socket5 proxy. Is there any way to solve this problem?

**Comment by Fleker** [comment]
It looks like your proxy service doesn't support HTTPS connections. You should see if there's a way to enable that.

**Comment by joy12202018** [comment]
ok,thank

**Comment by comsaint** [comment]
I come across this issue recently, and my trouble is I am behind corporate firewall and have little control with proxy setting, and AFAIK the port for SSL is closed too. Is there any way to get around?

**Comment by Fleker** [comment]
HTTPS is required.
