### ISSUE TITLE
Google Assistant SDK on Android NDK

### ISSUE THREAD

**Issue by Nitya05** [googlesamples/assistant-sdk-cpp#4]
Is there a way to use Google Assistant SDK(using gRPC c++) on Android NDK?

**Comment by Fleker** [comment]
Hypothetically you can take a look at [the C++ sample](github.com/googlesamples/assistant-sdk-cpp) and adapt it to the NDK. The protobuf can be converted to C++. However, the C++ sample depends on a different set of audio APIs so there may need to be a fair amount of redesign.

**Comment by Nitya05** [comment]
I am using AudioInputFile and have written the interfaces to make it work on the NDK. But, there are some issues in the build procedure; I have successfully built protobuf for NDK, but I'm unable to build gRPC for the same.

**Comment by Fleker** [comment]
You cannot build gRPC in the C++ sample above? It seems like [gRPC](https://github.com/grpc/grpc/) does not have NDK build scripts, but there is [a PR](https://github.com/grpc/grpc/pull/11329/files) on compiling for Android. The PR is open, and I've never run it, but it may resolve the build issues.
