### ISSUE TITLE
About the Terms of Service

### ISSUE THREAD

**Issue by joy12202018** [googlesamples/assistant-sdk-cpp#44]
Some questions about the terms of service want to ask。

Our company needs to make a smart speaker, intends to implant c++ code, would like to ask if this code needs to be commercial, in addition to complying with the open source protocol, which protocols do you need to comply with Google? Or is there a charge for using this code? Or do you only need to follow the open source to open source this code?

What resources does Google offer (such as music, alarm clocks, maps, navigation, etc.) for our developers? For example, music, can you play the music of a third-party platform on a smart speaker through Google Assistant? If so, are there any agreements that need to be adhered to or need to be charged accordingly? If you need to pay, does Google need to charge in this regard? If you access a third party, do you need to apply for permission to use the three-party function, or do you need to solve the three-party permission to use it smoothly?

How do I know what resources Google has provided for our developers? (Google Assistant should be able to complete a request and response through Action. Actions Directory should be product-related Actions made by other companies themselves. I know only this, but still do not know where to know Google offers Resources.) If these resources are listed in the Actions Directory, where can you know how to implement the above music playback function?

There is a bit of a headache about the terms of service recently, but there is a need to understand, so I would like to ask, I hope there are some directions. Thank you.

**Comment by Fleker** [comment]
You should probably consult your company's legal counsel with regards to the [terms of service](https://developers.google.com/assistant/sdk/terms-of-service), as I'm not qualified to give legal advice.  In terms of launching a commercial product, you should fill out [the form on the Launch page](https://developers.google.com/assistant/sdk/interest).

Music is one resource that is not available through the SDK right now. Alarms and timers are only available in the library, not the service API. Maps and navigation will give results.

**Comment by joy12202018** [comment]
Thank you for your answer.

Still want to ask a more stupid question. I understand that the Google Developer Additional Terms have three parts: Google APIs Terms of Service / Google Developers Site Terms of Service / Site Policies. I don't know which C++ code you provide belongs to which one?

Because now is only the stage of understanding, whether it is really used or not requires further understanding. So I would like to ask where can I consult the Google Assistant related questions? Can you only ask questions through the Launch page?

Thank you.

**Comment by joy12202018** [comment]
Thank for your Patiently reply.
