### ISSUE TITLE
make run_assistant fails on Ubuntu 18.04 with undefined reference to symbol '_ZN4grpc6g_glipE'

### ISSUE THREAD

**Issue by isbiliroglu** [googlesamples/assistant-sdk-cpp#47]
All the instructions were fine (download, make, install etc) until the one at the end failing to make run_assistant with: embedded_assistant.grpc.pb.o: undefined reference to symbol '_ZN4grpc6g_glipE'

g++ /Downloads/assistant-sdk-cpp/googleapis/gens/google/assistant/embedded/v1alpha2/embedded_assistant.pb.o /Downloads/assistant-sdk-cpp/googleapis/gens/google/assistant/embedded/v1alpha2/embedded_assistant.grpc.pb.o googleapis.ar src/base64_encode.o src/json_util.o src/audio_input_alsa.o src/audio_output_alsa.o src/audio_input_file.o src/run_assistant_audio.o  -lm  -lgrpc_cronet -Wl,--no-as-needed -lgrpc++_reflection -Wl,--as-needed -lprotobuf -lpthread -ldl  -o run_assistant_audio
/usr/bin/ld: /Downloads/assistant-sdk-cpp/googleapis/gens/google/assistant/embedded/v1alpha2/embedded_assistant.grpc.pb.o: undefined reference to symbol '_ZN4grpc6g_glipE'

Any idea what might have gone wrong here?

**Comment by isbiliroglu** [comment]
Hmm.
I did little bit of digging on the error line and realized that the needed libraries grpc and grpc++ was not there, hence the link failure. This missing symbol was in fact in: in grpc++ lib:

readelf -s  /usr/local/lib/libgrpc++.so | grep _ZN4grpc6g_glipE 
   425: 0000000000257e10     8 OBJECT  GLOBAL DEFAULT   25 _ZN4grpc6g_glipE
The reason for failure is, Makefile's LDFLAGS did not add these dependent libs to itself.
The main Makefile configures these library dependencies with pkg-config but only if pkg-config is installed:

PKG_CONFIG ?= pkg-config
HAS_PKG_CONFIG ?= $(shell command -v $(PKG_CONFIG) >/dev/null 2>&1 && echo true || echo false)
ifeq ($(HAS_PKG_CONFIG),true)
GRPC_GRPCPP_CFLAGS=`pkg-config --cflags grpc++ grpc`
GRPC_GRPCPP_LDLAGS=`pkg-config --libs grpc++ grpc`
ALSA_CFLAGS=`pkg-config --cflags alsa`
ALSA_LDFLAGS=`pkg-config --libs alsa`

In my Ubuntu, they were not, so, it wasn't able to use these libraries.
This seems to be a bug on "build instructions" on the web page. 
It needs to add pkg-config (and possibly pkgconf too) to the list there...
It worked for me once I did it on Ubuntu apt install.

Best,
Hakan

**Comment by codingspirit** [comment]
I meet the same issue when trying to build on Debian. It can be fixed by apt-get install pkg-config

**Comment by mpoullet** [comment]
@Fleker maybe consider closing this issue as #49 got merged.

**Comment by Fleker** [comment]
Thanks.
