### ISSUE TITLE
could windows version work？

### ISSUE THREAD

**Issue by sunjunlishi** [googlesamples/assistant-sdk-cpp#5]
I'm working on windows；I'm compiling GRPC, and protobuf is under Windows。i think it  will work

**Comment by sunjunlishi** [comment]
![qq 20171017104237](https://user-images.githubusercontent.com/11845664/31644273-f6445b96-b327-11e7-9b1f-87024bc8a4a0.png)
![qq 20171017104251](https://user-images.githubusercontent.com/11845664/31644274-f683171e-b327-11e7-9601-0810c6e1d77e.png)
i think some is no using

**Comment by Fleker** [comment]
Thus far it has only been tested with Ubuntu and ALSA.

**Comment by sunjunlishi** [comment]
i am not using alsa,using file
else {
    std::ifstream audio_file(audio_input_source);
}
;so if Grpc pass.

**Comment by sunjunlishi** [comment]
windows no libcurl4-openssl-dev

**Comment by sunjunlishi** [comment]
windows no libcurl4-openssl-dev

**Comment by sunjunlishi** [comment]
libcurl4-openssl-dev has nothing use，using the newest curl,is ok;
and crypto,ssl is ok.
google api ,i using ubuntu,in windows,has little error
![qq 20171018134141](https://user-images.githubusercontent.com/11845664/31702530-274c6192-b40a-11e7-8cd2-0a0ec281c6c3.png)
Anyway, the compiler succeeded
