### ISSUE TITLE
json_util_test.cc:23:75: error: ‘GetCustomResponseOrNull’

### ISSUE THREAD

**Issue by jwinarske** [googlesamples/assistant-sdk-cpp#53]
Where's the implementation of GetCustomResponseOrNull supposed to be?  Grepping the build tree, I see no sign of it.

```
src/json_util_test.cc:23:75: error: ‘GetCustomResponseOrNull’ was not declared in this scope
   std::unique_ptr<std::string> result = GetCustomResponseOrNull(input_json);
```

**Comment by Fleker** [comment]
When do you run into that error?

**Comment by jwinarske** [comment]
I was trying to build json_util_test.cc thinking it was a valid test case.  Just looking at the contents, I'm dropping it ;)
