### ISSUE TITLE
Is it possible to reuse grpc::Channel and EmbeddedAssistant::Stub?

### ISSUE THREAD

**Issue by codingspirit** [googlesamples/assistant-sdk-cpp#57]
In run_assistant_text demo code a new EmbeddedAssistant::Stub and grpc::Channel will be created when a new text input is coming.
Is is possible to create grpc::Channel and EmbeddedAssistant::Stub only once instead of creating a new one every time?
When I trying to do this, demo will block at second time stream->Read(&response)
```
    // Begin a stream.
    auto channel = CreateChannel(api_endpoint);
    std::unique_ptr<EmbeddedAssistant::Stub> assistant(
        EmbeddedAssistant::NewStub(channel));

    grpc::ClientContext context;
    context.set_fail_fast(false);
    context.set_credentials(call_credentials);

    std::shared_ptr<ClientReaderWriter<AssistRequest, AssistResponse>> stream(
        std::move(assistant->Assist(&context)));

    AssistResponse response;
    //Write request and read response
    stream->Write(request);
    while(stream->Read(&response)){// this read will success
     ...
   }
  //Do it again
    stream->Write(request);
    while(stream->Read(&response)){// get blocked at here forever
     ...
   }
```
Thanks in advance.

**Comment by Fleker** [comment]
I think the gRPC channel can be the same, but the Stub will need to be created alongside each request.

**Comment by codingspirit** [comment]
> I think the gRPC channel can be the same, but the Stub will need to be created alongside each request.
