### ISSUE TITLE
compile err with assistant-sdk-cpp

### ISSUE THREAD

**Issue by AbhishekFishy** [googlesamples/assistant-sdk-cpp#6]
While following following steps 

cd ../
git clone https://github.com/googlesamples/assistant-sdk-cpp.git

cd assistant-sdk-cpp/
make run_assistant

I get Compile error

 -I./grpc -I./src/  -c -o src/json_util.o src/json_util.cc
src/json_util.cc:21:36: fatal error: src/core/lib/json/json.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'src/json_util.o' failed
make: *** [src/json_util.o] Error 1

Actually src/core/ does not exist

m@pe:~/GVA/assistant-sdk-cpp$ 
m@pe:~/GVA/assistant-sdk-cpp$ pwd
/home/m/GVA/assistant-sdk-cpp
m@pe:~/GVA/assistant-sdk-cpp$ 
m@pe:~/GVA/assistant-sdk-cpp$ ls 
CONTRIBUTING.md     googleapis.ar  Makefile  README.md  src
get_credentials.sh  LICENSE        proto     resources
m@pe:~/GVA/assistant-sdk-cpp$ 
m@pe:~/GVA/assistant-sdk-cpp$ 
m@pe:~/GVA/assistant-sdk-cpp$ ls src/
assistant_config.h   audio_output_alsa.cc           embedded_assistant.pb.o
audio_input_alsa.cc  audio_output_alsa.h            json_util.cc
audio_input_alsa.h   audio_output_alsa.o            json_util.h
audio_input_alsa.o   embedded_assistant.grpc.pb.cc  json_util_test.cc
audio_input_file.cc  embedded_assistant.grpc.pb.h   run_assistant.cc
audio_input_file.h   embedded_assistant.grpc.pb.o   scope_exit.h
audio_input_file.o   embedded_assistant.pb.cc       service_account_util.cc
audio_input.h        embedded_assistant.pb.h        service_account_util.h
m@pe:~/GVA/assistant-sdk-cpp$ 
m@pe:~/GVA/assistant-sdk-cpp$

**Comment by Fleker** [comment]
Looks like that may be in a sub-project, like gRPC and one may need to enter a separate directory. I will look into the compiler error.

**Comment by Fleker** [comment]
Can you try doing `export GOOGLEAPIS_GENS_PATH=`pwd`/googleapis/gens` instead?

I'm working on updating the Makefile now to be a bit more helpful

**Comment by AbhishekFishy** [comment]
Thanks Fleker,

In Makefile changed   
GRPC_SRC_PATH ?= ./grpc
to
GRPC_SRC_PATH ?= ../grpc

now it compiles further but fails on openssl as shown under. I'll install openssl dev

In file included from src/service_account_util.cc:23:0:
../grpc/src/core/lib/security/credentials/jwt/json_token.h:23:25: fatal error: openssl/rsa.h: No such file or directory

**Comment by Fleker** [comment]
I'm working on fixing some of the build components. I've found a few issues since the last time I compiled it.

Did you do the same thing for the `GOOGLEAPIS_GENS_PATH` var in the Makefile?

**Comment by AbhishekFishy** [comment]
Yes, same change is needed for both

GRPC_SRC_PATH ?= ../grpc
GOOGLEAPIS_GENS_PATH ?= ../googleapis/gens

**Comment by AbhishekFishy** [comment]
This change was also needed

SSL_PATH ?= ../grpc/third_party/boringssl/include/

CPPFLAGS += -I/usr/local/include -pthread -I$(GOOGLEAPIS_GENS_PATH) \
            -I$(GRPC_SRC_PATH) -I./src/ -I$(SSL_PATH)

**Comment by Fleker** [comment]
That's an interesting change as I've never had to make that.

**Comment by AbhishekFishy** [comment]
I've connected a Mic and Earplugs and have tested both then run it as under

./run_assistant --audio_input ALSA_INPUT --credentials_file ./My-First-Project-4e60ff8cbdfe.json --credentials_type SERVICE_ACCOUNT

​When I give above command I get Audio o/p "Give me permission to help you"

When I give this command and make a voice query through Mic "What is weather today", even in this case I get Audio o/p as mentioned above. It does not answer query.

I'd created a project "My First Project"

Project ID
sustained-valor-186206
Project number
996445381799

It has Service account as under
abhi-service@sustained-valor-186206.iam.gserviceaccount.com 

and Role is Owner

I checked API and Service "Google Assistant API " is enabled.

When I check API Services -> Dashboard : I'm able to see traffic there.
Any Idea why am I not gettig response?

**Comment by Fleker** [comment]
You may need to enable some features in your account's [Activity Controls](https://myaccount.google.com/activitycontrols) .

**Comment by AbhishekFishy** [comment]
Hi Fleker,
Following are enabled 

Web & App Activity
Location History
Device Information
Voice & Audio Activity 
YouTube Search History
YouTube Watch History

For Voice & Audio Activity => Manage Activity=> I see only 1 item for yesterday. Says "transcript not available". I can hear some audio for this activity. Its some garbage Audio.

**Comment by Fleker** [comment]
Thanks. Would it be possible for you to try a `USER_ACCOUNT`. I'll look into why a service account may be having issues.

**Comment by AbhishekFishy** [comment]
That works

./run_assistant --audio_input ALSA_INPUT --credentials_file ./credentials.json --credentials_type USER_ACCOUNT
With above I'm able to get reasonable response 


./run_assistant --audio_input ./resources/switch_to_channel_5.raw --credentials_file ./credentials.json --credentials_type USER_ACCOUNT

With above Response : Sorry I can not help with that yet.

**Comment by Fleker** [comment]
I'll look into why there's a problem with the service account. In the meantime I'll close the issue since it seems like you've resolved it.

**Comment by Rohit3649** [comment]
I am trying to build Google Assistant "googlesamples/assistant-sdk-cpp".

For Linux i am able to build and its working fine. I am trying to make one sample application for Tizen platform and trying to make one GBS build.
I am able to build protobuf and GRPC but when i am trying to build Google Assistant using spec file its giving below error ->
[    9s] src/run_assistant.cc:39:70: fatal error: google/assistant/embedded/v1alpha2/embedded_assistant.pb.h: No such file or directory
[    9s]  #include "google/assistant/embedded/v1alpha2/embedded_assistant.pb.h"


i tried to build googleapis separately but its giving below error ->
[    9s] protoc --proto_path=.:/usr/local/include --cpp_out=./gens --grpc_out=./gens --plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin google/api/label.proto
[    9s] protoc --proto_path=.:/usr/local/include --cpp_out=./gens --grpc_out=./gens --plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin google/api/usage.proto
[    9s] /usr/local/bin/grpc_cpp_plugin: program not found or is not executable
[    9s] --grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
[    9s] Makefile:44: recipe for target 'google/api/label.pb.cc' failed
[    9s] make: *** [google/api/label.pb.cc] Error 1
[    9s] make: *** Waiting for unfinished jobs....


I tried with "GRPC_SRC_PATH ?= ../grpc" this change in GA Makefile but its not woking :(

do i need to build googleapis separately ? and link with provide the same for GA as "BuildRequires :"
if so please help me to resolve above issue.
