### ISSUE TITLE
Could you make repositories grpc and googleapis submodule of assistant-skd-cpp

### ISSUE THREAD

**Issue by robinali** [googlesamples/assistant-sdk-cpp#60]
I am working on MIPS cross-compiling for google assistant here.
But no luck finding a stable build that MIPS support yet.

What happened here is, both GRPC and googleapis are pretty active and people enjoying to use latest standard APIs. But MIPS is out of date (the one I am using is year 2016) and not supporting them.

Hence, I need to find a older version of GRPC and googleapis that Okay with google assistant while MIPS support it.

This will be much easier if the GRPC and googleapis is submodule of this project. That it will use a stable folk (image copy) of the original project back to the date of release time of google assistant. And extra new features won't be included.
For example: the initial commit will associate the repositories of GRPC and googleapis back in Aug 23, 2017. With submodule set up, we can re-build the original ones now exactly same as 1 years before, and it works.

Please consider the feature improvement. Thank you.

If submodule is not a option, please document the commit # of GRPC and googleapis you use when you conduct release? It really helps my case.

**Comment by robinali** [comment]
Hi @Fleker ,
Thank you for your quick reply.
I will try the grpc v1.11.0 tomorrow.

Hope they works. If so, I will create a script for cross-compiling.
Finger crossed.

**Comment by Fleker** [comment]
For the googleapis repo I guess I've been using the master branch at HEAD.

**Comment by robinali** [comment]
@Fleker 

Yes you are. And latest googleapis is stable.

BTW, when I build with GRPC v1.17.0 and master sometime the text and file test will crash.
If you need more details, let me know. :D

Super busy for now, I will add this to my to-do and get some sum up about cross-compiling for embedded MIPS later. A bit complex than I thought.

**Comment by robinali** [comment]
Update latest googleeapis will get error when build:
protoc --proto_path=.:/usr/local/include --cpp_out=./gens --grpc_out=./gens --plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin google/pubsub/v1/pubsub.proto
google/pubsub/v1/pubsub.proto:33:8: Option "ruby_package" unknown.
Makefile:44: recipe for target 'google/pubsub/v1/pubsub.pb.cc' failed
make: *** [google/pubsub/v1/pubsub.pb.cc] Error 1

Rolling back with command in "./googleapis/" with command "git checkout  980cdfa" works.

@Fleker Consider add a version of project google APIs as well?

**Comment by Fleker** [comment]
Done.
