### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by zuowanbushiwo** [googlesamples/assistant-sdk-cpp#61]
Hi 
   Thank you very much, I am very interested in this project， But I got an error when I tried to compile it，Can you help me?
   As：
[HOSTCXX] Compiling src/compiler/cpp_plugin.cc
[HOSTLD]  Linking /home/yangjie/google_assistant/assistant-sdk-cpp/grpc/bins/opt/grpc_cpp_plugin
[HOSTCXX] Compiling src/compiler/csharp_plugin.cc
[HOSTLD]  Linking /home/yangjie/google_assistant/assistant-sdk-cpp/grpc/bins/opt/grpc_csharp_plugin
[HOSTCXX] Compiling src/compiler/node_plugin.cc
[HOSTLD]  Linking /home/yangjie/google_assistant/assistant-sdk-cpp/grpc/bins/opt/grpc_node_plugin
[HOSTCXX] Compiling src/compiler/objective_c_plugin.cc
[HOSTLD]  Linking /home/yangjie/google_assistant/assistant-sdk-cpp/grpc/bins/opt/grpc_objective_c_plugin
[HOSTCXX] Compiling src/compiler/php_plugin.cc
[HOSTLD]  Linking /home/yangjie/google_assistant/assistant-sdk-cpp/grpc/bins/opt/grpc_php_plugin
[HOSTCXX] Compiling src/compiler/python_plugin.cc
[HOSTLD]  Linking /home/yangjie/google_assistant/assistant-sdk-cpp/grpc/bins/opt/grpc_python_plugin
[HOSTCXX] Compiling src/compiler/ruby_plugin.cc
[HOSTLD]  Linking /home/yangjie/google_assistant/assistant-sdk-cpp/grpc/bins/opt/grpc_ruby_plugin
[PROTOC]  Generating protobuf CC file from src/proto/grpc/channelz/channelz.proto
[GRPC]    Generating gRPC's protobuf service CC file from src/proto/grpc/channelz/channelz.proto
[libprotobuf FATAL google/protobuf/generated_message_util.cc:794] CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning): 
--grpc_out: protoc-gen-grpc: Plugin killed by signal 6.
make: *** [/home/yangjie/google_assistant/assistant-sdk-cpp/grpc/gens/src/proto/grpc/channelz/channelz.grpc.pb.cc] Error 1

   Much like this person's description：
   https://github.com/protocolbuffers/protobuf/issues/5923

My computer info：
   DISTRIB_ID=Ubuntu
   DISTRIB_RELEASE=14.04
   DISTRIB_CODENAME=trusty
   DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"

thanks！

**Comment by zuowanbushiwo** [comment]
thanks, use test_all.sh build successfull。 maybe this key point：git checkout v1.11.0

**Comment by pronoy136** [comment]
see comment on #62
