### ISSUE TITLE
google_assistant_sdk for C++

### ISSUE THREAD

**Issue by pronoy136** [googlesamples/assistant-sdk-cpp#62]
Ask Question

0

using setup process at "https://github.com/googlesamples/assistant-sdk-cpp" while trying to execute the step :- ./run_assistant_file --input ./resources/weather_in_mountain_view.raw --output ./response.wav --credentials ./credentials.json

I am getting the below error:- 
terminate called without an active exception 
Aborted (core dumped)

while the setup executes successfully executes for :- echo "what time is it" | ./run_assistant_text --credentials ./credentials.json

**Comment by pronoy136** [comment]
Also,

In step 3 of “Build Project” subsection google sdk installation after commands:-
export LDFLAGS="$LDFLAGS -lm"
cd ${GRPC_PATH}
make clean
make
sudo make install

An error might occur.

Error:
[libprotobuf FATAL google/protobuf/generated_message_util.cc:794] CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning):
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning):
--grpc_out: protoc-gen-grpc: Plugin killed by signal 6.

solution:-
The error is due to pthread in protobuf that was not configured properly. Executing below command from protobuf folder to solve this issue before using “sudo make install” command:-
•	pkg-config --cflags --libs protobuf 	# print compiler flags and linker flags
•	./configure CXXFLAGS="$(pkg-config --cflags protobuf)" LIBS="$(pkg-config --libs protobuf)"
•	make
•	sudo make install
•	go to grpc folder and run "make" command

after this only installation was successful and ./run_assistant_text worked

**Comment by pronoy136** [comment]
can anyone help with this issue, or give a solution

**Comment by Fleker** [comment]
It seems like you already found the solution

**Comment by pronoy136** [comment]
I have found solution to issue #61 , this is however a seperate issue please check this issue , it has not yet been resolved @Fleker 

 ./run_assistant_file --input ./resources/weather_in_mountain_view.raw --output ./response.wav --credentials ./credentials.json

is still not working after following all installation steps

so please check it on your end and re-open this issue.

you can try installing on a fresh vm copy for ubuntu14.04 and test it yourself , 

./run_assistant_file --input ./resources/weather_in_mountain_view.raw --output ./response.wav --credentials ./credentials.json

would  NOT WORK

**Comment by Fleker** [comment]
I just ran the build and test scripts in a CI system and it was successful.

**Comment by pronoy136** [comment]
I am still getting :-

terminate called without an active exception
Aborted (core dumped)

for 

./run_assistant_file --input ./resources/weather_in_mountain_view.raw --output ./response.wav --credentials ./credentials.json

**Comment by Fleker** [comment]
I'm running this script https://github.com/googlesamples/assistant-sdk-cpp/blob/master/tests/test_all.sh without issue, which runs

```
./run_assistant_file --input ./resources/weather_in_mountain_view.raw \
  --output /tmp/google-assistant-sdk-audio-output.raw \
  --credentials ./credentials.json \
  | grep "Mountain View"
```

It's unclear where the failure may be happening on your side.
