### ISSUE TITLE
Response to smart home action

### ISSUE THREAD

**Issue by eron93br** [googlesamples/assistant-sdk-cpp#71]
Hey, can you confirm that this version o SDK in C++ does not have support to actions response?

I'm trying to get a JSON with an answer of a smart home action but I'm getting an empty JSON. 

I tried to get the JSON using the method **device_request_json** listed on the DOCs of Package google.assistant.embedded.v1alpha2. 

```   
     actionObject = response.device_action().device_request_json(); 
```

**Comment by Fleker** [comment]
Smart home responses are not available through the API. Conversational actions do get sent back.
