### ISSUE TITLE
make run_assistant failed!

### ISSUE THREAD

**Issue by kobeya** [googlesamples/assistant-sdk-cpp#75]
Cat log as follow:
g++ -std=c++11 `pkg-config --cflags grpc++ grpc` `pkg-config --cflags alsa` -I/home/pc/workspace/2th_GVA/04th_build_assistant-sdk-cpp/assistant-sdk-cpp/googleapis/gens -I./grpc -I./src  -c -o src/assistant/base64_encode.o src/assistant/base64_encode.cc
g++ -std=c++11 `pkg-config --cflags grpc++ grpc` `pkg-config --cflags alsa` -I/home/pc/workspace/2th_GVA/04th_build_assistant-sdk-cpp/assistant-sdk-cpp/googleapis/gens -I./grpc -I./src  -c -o src/assistant/json_util.o src/assistant/json_util.cc
In file included from ./grpc/src/core/lib/json/json.h:30:0,
                 from src/assistant/json_util.cc:20:
./grpc/src/core/lib/gprpp/string_view.h:33:10: fatal error: absl/strings/string_view.h: No such file or directory
 #include "absl/strings/string_view.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'src/assistant/json_util.o' failed
make: *** [src/assistant/json_util.o] Error 1
_________________________________________________________________________
Somebudy know it?

**Comment by kobeya** [comment]
By the way,my pc version
Ubuntu 18.04.4 LTS

**Comment by maimang9** [comment]
when i compile the sdk i copy "grpc/src/core/lib/json" to the "src" dir
assistant-sdk-cpp$ ls src/core/lib/json/
json.cc  json_common.h	json.h	json_reader.cc	json_reader.h  json_string.cc  json_writer.cc  json_writer.h

and change the json_util.cc include file
assistant-sdk-cpp$ git diff src/assistant/json_util.cc
diff --git a/src/assistant/json_util.cc b/src/assistant/json_util.cc
old mode 100644
new mode 100755
index f288053..36dc49a
--- a/src/assistant/json_util.cc
+++ b/src/assistant/json_util.cc
@@ -17,7 +17,7 @@ limitations under the License.
 #include "assistant/json_util.h"
 
 extern "C" {
-#include <src/core/lib/json/json.h>
+#include "core/lib/json/json.h"
 }
 
 #include <cstring>

**Comment by kobeya** [comment]
@maimang9 
Thank you for you reply.
I  try my code  as your way,but it still not working for me.
when i try your way, i get the follow log:

assistant-sdk-cpp$ make run_assistant
g++ -std=c++11 `pkg-config --cflags grpc++ grpc` `pkg-config --cflags alsa` -I./googleapis/gens -I./grpc -I./src  -c -o src/assistant/json_util.o src/assistant/json_util.cc
In file included from /usr/include/c++/7/map:60:0,
                 from ./src/core/lib/json/json.h:26,
                 from src/assistant/json_util.cc:21:
/usr/include/c++/7/bits/stl_tree.h:141:3: error: template with C linkage
   template<typename _Key_compare>
   ^~~~~~~~
/usr/include/c++/7/bits/stl_tree.h:215:3: error: template with C linkage
   template<typename _Val>
   ^~~~~~~~
/usr/include/c++/7/bits/stl_tree.h:247:3: error: conflicting declaration of C function ‘const std::_Rb_tree_node_base* std::_Rb_tree_increment(const std::_Rb_tree_node_base*)’
   _Rb_tree_increment(const _Rb_tree_node_base* __x) throw ();

and so on....

thank you again!

**Comment by Fleker** [comment]
Can you tell what version of gRPC you're checking out? The [CI script](https://github.com/googlesamples/assistant-sdk-cpp/blob/master/tests/build.sh#L21) pins to v1.11.0

**Comment by kobeya** [comment]
@Fleker 
wa!!!
perfect!!!
Just fix it with your suggestion!
and thank you @maimang9 ,your ideas may help others!
