### ISSUE TITLE
Unable to install gRPC based on instructions in README.md

### ISSUE THREAD

**Issue by tewarid** [googlesamples/assistant-sdk-cpp#78]
I tried to build gRPC based on instructions in README.md for the Raspberry Pi 3, but the following step (line 59)

```bash
sudo make install
```

fails with

```
grpc Installing via 'make' is no longer supported. Use cmake or bazel instead.
```

I was able to install it based on cmake instructions at [https://github.com/grpc/grpc/blob/master/BUILDING.md](/grpc/grpc/blob/master/BUILDING.md).

**Comment by darwinmorris** [comment]
I am having a similar issue, did you find a solution to your problem?

**Comment by tewarid** [comment]
I went down a rabbit hole of build errors with gRPC master hence decided to build an older version.

In README.md, instead of

```bash
git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
```

execute

```bash
git clone -b v1.23.0 https://github.com/grpc/grpc
```

You may get build errors in boringssl due to warnings being reported as errors but existing issues can help solve that e.g. grpc/grpc#18819.

**Comment by tewarid** [comment]
Duplicate of #76.

**Comment by tewarid** [comment]
I was able to get sample running on a Raspberry Pi 3 Model B Rev 1.2 with Raspbian GNU/Linux 10 (buster), with minor changes at https://github.com/tewarid/assistant-sdk-cpp/tree/grpc-v1.30.2. I can open a PR if this sample is still an active project.
