### ISSUE TITLE
action question?

### ISSUE THREAD

**Issue by sunjunlishi** [googlesamples/assistant-sdk-cpp#8]
Why have we succeeded in validting action ,and to test our hardware; looser and easier to develop the Google cloud

**Comment by sunjunlishi** [comment]
Hello, 
We will soon be launching Actions on Google in en-IN (Indian English) to consumers. After our consumer launch, your deployed app will automatically work on all Assistant enabled devices with the language set to en-IN, with no additional work needed from you. 
To prepare for the launch we suggest you do the following: 
Try your app for the en-IN language in the simulator. See the docs for how to test other languages in the simulator. 
If you elected to match a user’s language setting, by default, the TTS voice your app uses on devices set to en-IN will have an Indian accent. If you’d prefer to keep your app’s existing English accent, customize the voice in the console. If you had already explicitly set a specific voice for your app, this setting will not be affected. See the docs for how to customize your voice. 
If you need to block your app from working in India, you can use the country/region blocking support in the console. See the docs for how to target countries. 
We plan to expand the number of languages we support over the coming months. To always be up to date, join our Google+ community and subscribe to our newsletter.

**Comment by sunjunlishi** [comment]
Google Assistant <assistant-noreply@google.com> 
发送至 我 
Hello Smart Home Developer, 
Thank you for submitting your app for review, and congratulations on getting this far in the process. Your app "xingtel" (with project ID "dev-XXXX") has passed the first review and the next step is to get your smart home device ‘Works with Assistant’ certified. 

Please fill out this intake form that Allion USA requires to begin validating your Smart Home integration. The set of QA test cases that will be run are described here. 

We work with a third-party certification vendor called Allion USA for device testing and certification. Please complete the form, and follow their instructions to continue on your journey. 
Action Required - Submit the following:
Send two sets of devices to the address in the intake form.
Include two of each device type you’re supporting. Those devices will not be returned.
Include setup instructions. If your app only works on certain versions of Android/iOS, include this information.
If you are a hub or an integration provider, include your most popular devices that will be covered by the Smart Home app being validated.
You should not have any special accounts that require whitelisting or other work done that is outside of what a typical consumer would experience.
If you device requires a subscription to be operated and tested the subscription services should be provided to Allion USA for free.
All servers must be in production prior to shipping devices to Allion USA. The app being verified will be considered as your production app.
Do not submit a QA or Dev environment app to be tested.

**Comment by Fleker** [comment]
I'm not sure what your question is. It appears that your email refers to Smart Home, not the Assistant SDK C++ sample. This may not be the best forum to ask.

**Comment by sunjunlishi** [comment]
ok
