### ISSUE TITLE
SSL handshake error on custom Android-x86 board

### ISSUE THREAD

**Issue by aspratyush** [googlesamples/assistant-sdk-cpp#9]
Hello google-assistant team,

I have built google-assistant (and dependencies) using Android NDK. When running the executable on Android-x86 emulator, the whole flow works and I get to hear the response (have added the plumbing logic to play it on Android).

However, when running the same on a custom Android-x86 board, the following handshake error shows up:
11-11 11:14:52.698 6980-9508/com.test.app E/GRPC: ssl_transport_security.c:921] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
11-11 11:14:52.892 6980-9508/com.test.app E/GRPC: ssl_transport_security.c:921] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
..
..
11-11 11:14:53.388 6980-9508/com.test.app E/GRPC: ssl_transport_security.c:921] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.

To get it to run on the emulator, I had to do the following:
1) set the environment variable GRPC_DEFAULT_SSL_ROOTS_FILE_PATH to point it to Google's PEM file (https://pki.google.com/roots.pem)
2) also pass this pem file location to https://github.com/googlesamples/assistant-sdk-cpp/blob/3b2d0e681fac8217b328cbd5c145eb4f094be36b/src/run_assistant.cc#L66

However, doing the same on the custom board does not help.

Any clues why this may be happening?

**Comment by Fleker** [comment]
`11-11 11:14:52.698`

Is that the date on the board? Is the incorrect date causing the SSL error?

**Comment by aspratyush** [comment]
Awesome catch! Thanks a ton :)

Doing the following on Android native shell resolved the issue:
$ date MMDDhhmmYYYY.ss; am broadcast -a android.intent.action.TIME_SET
